{{ config(materialized='table') }}

SELECT
    alb.ALBUMID AS ALBUM_ID,
    alb.TITLE AS ALBUM_TITLE,
    alb.PRODUCTIONYEAR AS ALBUM_PRODUCTIONYEAR,
    alb.CD_NUMBER AS ALBUM_CD_NUMBER,
    art.NAME AS ALBUM_ARTIST_NAME,
    art.BIRTHYEAR AS ALBUM_ARTIST_BIRTHYEAR,
    art.COUNTRY AS ALBUM_ARTIST_COUNTRY

FROM
    {{ source('EXAM_SNOWFLAKE', 'ALBUM') }} alb
JOIN
    {{ source('EXAM_SNOWFLAKE', 'ARTIST') }} art ON (alb.ARTISTID = art.ARTISTID)

