{{ config(materialized='table') }}

SELECT
    t.TRACKID AS TRACK_ID,
    pl.PLAYLISTID AS PLAYLIST_ID,
    alb.ALBUMID AS ALBUM_ID,
    t.MEDIATYPEID AS MEDIATYPE_ID,
    t.GENREID AS GENRE_ID,
    t.TITLE AS TRACK_TITLE,
    t.COMPOSER AS COMPOSER,
    t.MILLISECONDS AS MILLISECONDS,
    t.BYTES AS BYTES,
    t.UNITPRICE AS UNITPRICE
FROM
    {{ source('EXAM_SNOWFLAKE', 'TRACK') }} t
JOIN
    {{ source('EXAM_SNOWFLAKE', 'ALBUM') }} alb ON (t.ALBUMID = alb.ALBUMID)
JOIN
    {{ source('EXAM_SNOWFLAKE', 'PLAYLISTTRACK') }} plt ON (t.TRACKID = plt.TRACKID)
JOIN
    {{ source('EXAM_SNOWFLAKE', 'PLAYLIST') }} pl ON (plt.PLAYLISTID = pl.PLAYLISTID)

